# Generated by Django 3.2.7 on 2022-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_go_site', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='summary',
            field=models.IntegerField(null=True),
        ),
    ]
