# Generated by Django 3.2.7 on 2022-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_go_site', '0005_application_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='summary',
            field=models.FloatField(null=True),
        ),
    ]
