# Generated by Django 3.2.7 on 2022-05-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_go_site', '0009_auto_20220522_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
