# Generated by Django 3.2.7 on 2022-05-23 15:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_go_site', '0010_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_ok', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('total_price', models.FloatField(null=True)),
                ('wallet', models.CharField(default='', max_length=26)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
