# Generated by Django 3.2.7 on 2022-05-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_go_site', '0011_auto_20220523_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='link',
            new_name='trade_url',
        ),
    ]
